- spiele/hase-und-igel/spielregeln/felder.adoc
Nehme an, dass hier ein "wenn" fehlt.
> corrected sentence

- software/server.adoc
Fixes https://github.com/CAU-Kiel-Tech-Inf/socha/issues/203
Ich habe die Dokumentation des TestClients angepasst und alle Überschriften ein Level befördert. Ich frage mich gerade, ob ich die Funktionalität des TestClients, die bis zu einem statistisch signifikanten Ergebnis spielt, auch dokumentieren soll.
> Update TestClient documentation

- spiele/piranhas/spielregeln/regeln.adoc
> Klarstellung bei gegnerischen Fischen im Weg

- docs
Ich habe dazu auch überlegt, ob `asciidoctor-extensions-lab` nicht einfach ein submodule sein sollte?
> Improve docs script

- software/einfuehrung-xml.adoc
- spiele/blokus/xml-dokumentation/spielverlauf.adoc
Should be rebase merged.
Btw, also contains my suggestion for a sensible commit message style for that repo. Since there are not many types of changes, the path is most important. I use a slightly abbreviated scheme, similar to my dotfiles: https://github.com/xerus2000/dotfiles/commits/master
> Update blokus xml doc for 21.1.0

- spiele/blokus/xml-dokumentation/spielstatus.adoc
- spiele/blokus/xml-dokumentation/spielverlauf.adoc
Updates to `validColors` are according to https://github.com/CAU-Kiel-Tech-Inf/backend/pull/345
> Add documentation for validColors and lastMoveMono

- software/server.adoc
Did this since a player didn't understand how to run the TestClient (that it has to be run from the terminal is the crucial addition)
> software/server: update, reformat and improve explanations

- hyperbook/book/spiele/penguins/xml.md
Completes the XML documentation
> penguins: add move types and coords system info to xml docs

- hyperbook/book/entwicklung/sauberer-programmierstil.md
> allgemein: fix typos

- README.md
- hyperbook/book/allgemein/index.md
- hyperbook/glossary/contest.md
- hyperbook/glossary/player.md
Setzt die Guidelines um, die intern bespochen wurden
> allgemein: fix gender

- hyperbook/book/spiele/penguins/xml.md
Adds additional info to help students
> penguins: add coordinate transformation formulas

- hyperbook/book/spiele/penguins/regeln.md
- hyperbook/book/spiele/penguins/xml.md
I hope I understood [this ](https://github.com/software-challenge/backend/blob/de424a85285bc7b5eb4fb054f002ac307e22863f/plugin/src/main/kotlin/sc/plugin2023/Board.kt#L65) piece of code correctly
> penguins: add gameserver implementation info

- hyperbook/book/spiele/penguins/regeln.md
> /penguins/regeln: More detailed description of the construction of a board

- hyperbook/book/entwicklung/abgabe.md
- hyperbook/book/entwicklung/einrichtung-der-entwicklungsumgebung.md
- hyperbook/book/entwicklung/index.md
- hyperbook/book/entwicklung/simpleclient-erweitern.md
> entwicklung: replace Zufallsspieler with Spielervorlage

- hyperbook/book/glossar.md
- hyperbook/book/spiele/penguins/xml.md
- hyperbook/glossary/xml-administration.md
> glossar: adds generic xml information to glossar

- hyperbook/book/entwicklung/abgabe.md
> abgabe: update build description

- hyperbook/book/bookmark.md
- hyperbook/book/index.md
To make the bookmarks more accessible, I added a section that contains the bookmarks.
> bookmark: add a bookmark section

- hyperbook/book/entwicklung/abgabe.md
> abgabe: remove build descriptions

- hyperbook/book/spiele/mississippi-queen/xml.md
Fixes the example xml move payload in the docs
> Fix move payload based on wireshark traffic

- hyperbook/book/spiele/25_hase-und-igel/xml.md
- hyperbook/book/xml/intro.md
- Update HUI xml documentation to match last year's style and content
- Fix some grammar and wording issues in the generic xml documentation
> 2025 XML documentation
